# Generated by Django 5.2.4 on 2025-08-02 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Edited'),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Old Content')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited At')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='messaging.message', verbose_name='Original Message')),
            ],
            options={
                'verbose_name': 'Message History',
                'verbose_name_plural': 'Message Histories',
                'ordering': ['-edited_at'],
            },
        ),
    ]
